# Generated by Django 5.0.3 on 2024-03-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('manufactury', 'Завод'), ('retailer', 'Розничный агент'), ('entrepreneur', 'Индивидуальный предприниматель')], default='manufactury', max_length=12, verbose_name='Категория юридического лица')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='эл.адрес')),
                ('street', models.CharField(max_length=150, verbose_name='улица')),
                ('building', models.CharField(max_length=10, verbose_name='дом, корпус, квартира')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='задолженность')),
                ('created', models.DateTimeField(verbose_name='создан')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='продукция')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='поставщик')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.country', verbose_name='cтрана')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.town', verbose_name='cтрана')),
            ],
        ),
    ]
