# Generated by Django 5.0.3 on 2024-03-09 10:06

import company.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='company',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', validators=[company.validators.validate_supplier], verbose_name='поставщик'),
        ),
    ]
