# Generated by Django 5.0.3 on 2024-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_created_alter_company_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='создан'),
        ),
    ]
