# Generated by Django 5.0.3 on 2024-03-09 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='company',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='поставщик'),
        ),
    ]
