# Generated by Django 5.0.3 on 2024-03-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_created_alter_company_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность'),
        ),
    ]
